### ISSUE TITLE
Problems with Meteor 1.3-beta 11

### ISSUE THREAD

**Issue by danrubins** [poetic/meteor-apple-purchases#1]
When I use this with Meteor 1.3 beta 11, it crashes as soon as I use IAP.buy. I think this is caused by a change in 1.3 with the way cordova is used. I'll investigate and let you know what I find out, but I wanted to give you a heads up.

**Comment by danrubins** [comment]
It looks like in Meteor 1.3, they upgraded Cordova dependencies to 4.0. Unfortunately, they also started prefixing Cordova category method names (see https://issues.apache.org/jira/browse/CB-8270) to avoid conflicts. There is a fix for this in j3k0/cordova-plugin-purchase PR #408 that resolves issue #398 on that project. The PR has not yet been accepted, but I was able to get things working again by switching the cordova dependency in my meteor project to https://github.com/mlmassey/cordova-plugin-purchase.git#cfbb0ca93032275d1f3e79b72be9f2c7c397b093

Unfortunately, this is not backward compatible with prior versions, so > Meteor 1.3, use https://github.com/mlmassey/cordova-plugin-purchase.git#cfbb0ca93032275d1f3e79b72be9f2c7c397b093
and Meteor 1.2 and below, use https://github.com/j3k0/cordova-plugin-purchase.git#3bd13373f6dd0d54128554a8458b4043fbefe45f

**Comment by JohnRodney** [comment]
@dhrubins Hey thank you for the report. We are still working on alot of apps in 1.2 and haven't gotten to practical uses for some of these repo's on 1.3.  Would you be interested in opening a PR with changes to the readme to explain this caveat?

**Comment by JohnRodney** [comment]
Thanks for the information docs have been adjusted. Closing this issue now.
